# site settings
title: Rachel Lee
subtitle: 
email: bokyounglee@berkeley.edu
description: Welcome to my creative space where I share my life and projects.
baseurl: # the subpath of your site, e.g. /blog
url: 
author: Rachel Lee
street_address: 
city: Berkeley
state: CA
zip_code: 94704 
country: USA
phone: +1(925)989-1451

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
linkedin_url: https://www.linkedin.com/in/leerach/
github_url: https://github.com/leerach
gitlab_url:
googleplus_url: 
facebook_url: 
instagram_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
